//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAddress.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressDetail
    {
        public int AddressID { get; set; }
        public int DistID { get; set; }
        public int CityID { get; set; }
        public string StreetName { get; set; }
        public string BuildingName { get; set; }
        public string LandMark { get; set; }
        public string FullAddress { get; set; }
        public string PinCode { get; set; }
    
        public virtual City City { get; set; }
        public virtual District District { get; set; }
    }
}
